export const COVERS = {
  inRainbows: '/covers/inRainbows.webp',
  forEmma: '/covers/forEmma.webp',
  twinFantasy: '/covers/twinFantasy.webp',
  care: '/covers/care.webp',
  artAngles: '/covers/artAngles.webp',
  melodrama: '/covers/melodrama.webp',
  ballads1: '/covers/ballads1.webp',
  brat: '/covers/brat.webp',
  igor: '/covers/igor.webp',
  legend: '/covers/legend.webp',
  nostalgiaUltra: '/covers/nostalgiaUltra.webp',
  moonRiver: '/covers/moonRiver.webp',
  blonde: '/covers/blonde.webp',
  carrieAndLowell: '/covers/carrieAndLowell.webp',
  lustForLife: '/covers/lustForLife.webp',
  episode2: '/covers/episode2.webp',
  bloom: '/covers/bloom.webp',
  channelOrange: '/covers/channelOrange.webp',
  ctrl: '/covers/ctrl.webp',
  funeral: '/covers/funeral.webp',
  awakeMyLove: '/covers/awakeMyLove.webp'
}